name: FreeBSD-14.1 clang-18.1

on: [push, pull_request]

jobs:
  freebsd-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - name: build with cmake in FreeBSD vm
      uses: vmactions/freebsd-vm@v1.1.5
      with:
        usesh: true
        prepare: |
          pkg install -y cmake ruby ruby32-gems rubygem-rake curl libevent

        run: |
          gem install Mxx_ru   # install ruby gem required for restinio dependency installation
          cd ext/restinio
          mxxruexternals       # install those restinio deps
          cd ../..
          cmake -S . -B build -DCMAKE_BUILD_TYPE=debug -DNOPCH=ON -DBINFUSE_TEST=OFF -DHIBP_TEST=ON
          cmake --build build
          
